### PR TITLE
Add ArchLinux Support

### PR DESCRIPTION
**Pull request by k0ste**

### CODE REVIEW

**Comment by pdellaert** [comment]
I see no dhcpd configuration (the script only writes a config when RedHat or Debian), why?

**Comment by k0ste** [comment]
Because systemd.

**Comment by pdellaert** [comment]
Don't know systemd all to well, but how is the dhcpd server configured then? As far as i can tell, you still need a /etc/dhcpd.conf file or something to tell it what subnet, options and fixed leases it needs to provide, no?

**Comment by k0ste** [comment]
I think you mistake, review the path one more time :)

**Comment by pdellaert** [comment]
Woops, you are completely correct! Sorry :)

**Pull request merged**
